//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Metricon.Silverlight.MetriconRetailSystem.Host.DocuSignWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocuSignWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBase))]
    public partial class DocuSignWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DocuSign_CreateAndSendEnvelopeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocuSign_SignInOfficeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocuSign_GetRecipientViewRestOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocuSign_GetRecipientOfEnvelopeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocuSign_VoidEnvelopeRestOperationCompleted;
        
        private System.Threading.SendOrPostCallback DocuSign_DownloadDocumentForEnvelopeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocuSignWebService() {
            this.Url = global::Metricon.Silverlight.MetriconRetailSystem.Host.Properties.Settings.Default.Metricon_Silverlight_MetriconRetailSystem_Host_DocuSignWebService_DocuSignWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DocuSign_CreateAndSendEnvelopeCompletedEventHandler DocuSign_CreateAndSendEnvelopeCompleted;
        
        /// <remarks/>
        public event DocuSign_SignInOfficeCompletedEventHandler DocuSign_SignInOfficeCompleted;
        
        /// <remarks/>
        public event DocuSign_GetRecipientViewRestCompletedEventHandler DocuSign_GetRecipientViewRestCompleted;
        
        /// <remarks/>
        public event DocuSign_GetRecipientOfEnvelopeCompletedEventHandler DocuSign_GetRecipientOfEnvelopeCompleted;
        
        /// <remarks/>
        public event DocuSign_VoidEnvelopeRestCompletedEventHandler DocuSign_VoidEnvelopeRestCompleted;
        
        /// <remarks/>
        public event DocuSign_DownloadDocumentForEnvelopeCompletedEventHandler DocuSign_DownloadDocumentForEnvelopeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_CreateAndSendEnvelope", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnvelopeResult DocuSign_CreateAndSendEnvelope([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] pdf, int pagenumber, string estimateID, string versiontype, string printtype, string versionnumber, SignerParameter[] signerpara, string anchorXOffset, string anchorYOffset, string application, string documenttype, string clientuserid, string emailsubject, string emailbody, string contractnumber) {
            object[] results = this.Invoke("DocuSign_CreateAndSendEnvelope", new object[] {
                        pdf,
                        pagenumber,
                        estimateID,
                        versiontype,
                        printtype,
                        versionnumber,
                        signerpara,
                        anchorXOffset,
                        anchorYOffset,
                        application,
                        documenttype,
                        clientuserid,
                        emailsubject,
                        emailbody,
                        contractnumber});
            return ((EnvelopeResult)(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_CreateAndSendEnvelopeAsync(byte[] pdf, int pagenumber, string estimateID, string versiontype, string printtype, string versionnumber, SignerParameter[] signerpara, string anchorXOffset, string anchorYOffset, string application, string documenttype, string clientuserid, string emailsubject, string emailbody, string contractnumber) {
            this.DocuSign_CreateAndSendEnvelopeAsync(pdf, pagenumber, estimateID, versiontype, printtype, versionnumber, signerpara, anchorXOffset, anchorYOffset, application, documenttype, clientuserid, emailsubject, emailbody, contractnumber, null);
        }
        
        /// <remarks/>
        public void DocuSign_CreateAndSendEnvelopeAsync(
                    byte[] pdf, 
                    int pagenumber, 
                    string estimateID, 
                    string versiontype, 
                    string printtype, 
                    string versionnumber, 
                    SignerParameter[] signerpara, 
                    string anchorXOffset, 
                    string anchorYOffset, 
                    string application, 
                    string documenttype, 
                    string clientuserid, 
                    string emailsubject, 
                    string emailbody, 
                    string contractnumber, 
                    object userState) {
            if ((this.DocuSign_CreateAndSendEnvelopeOperationCompleted == null)) {
                this.DocuSign_CreateAndSendEnvelopeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_CreateAndSendEnvelopeOperationCompleted);
            }
            this.InvokeAsync("DocuSign_CreateAndSendEnvelope", new object[] {
                        pdf,
                        pagenumber,
                        estimateID,
                        versiontype,
                        printtype,
                        versionnumber,
                        signerpara,
                        anchorXOffset,
                        anchorYOffset,
                        application,
                        documenttype,
                        clientuserid,
                        emailsubject,
                        emailbody,
                        contractnumber}, this.DocuSign_CreateAndSendEnvelopeOperationCompleted, userState);
        }
        
        private void OnDocuSign_CreateAndSendEnvelopeOperationCompleted(object arg) {
            if ((this.DocuSign_CreateAndSendEnvelopeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_CreateAndSendEnvelopeCompleted(this, new DocuSign_CreateAndSendEnvelopeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_SignInOffice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnvelopeResult DocuSign_SignInOffice([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] pdf, int pagenumber, string estimateID, string versiontype, string printtype, string versionnumber, SignerParameter[] signerpara, string anchorXOffset, string anchorYOffset, string application, string documenttype, string emailsubject, string emailbody, string contractnumber) {
            object[] results = this.Invoke("DocuSign_SignInOffice", new object[] {
                        pdf,
                        pagenumber,
                        estimateID,
                        versiontype,
                        printtype,
                        versionnumber,
                        signerpara,
                        anchorXOffset,
                        anchorYOffset,
                        application,
                        documenttype,
                        emailsubject,
                        emailbody,
                        contractnumber});
            return ((EnvelopeResult)(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_SignInOfficeAsync(byte[] pdf, int pagenumber, string estimateID, string versiontype, string printtype, string versionnumber, SignerParameter[] signerpara, string anchorXOffset, string anchorYOffset, string application, string documenttype, string emailsubject, string emailbody, string contractnumber) {
            this.DocuSign_SignInOfficeAsync(pdf, pagenumber, estimateID, versiontype, printtype, versionnumber, signerpara, anchorXOffset, anchorYOffset, application, documenttype, emailsubject, emailbody, contractnumber, null);
        }
        
        /// <remarks/>
        public void DocuSign_SignInOfficeAsync(byte[] pdf, int pagenumber, string estimateID, string versiontype, string printtype, string versionnumber, SignerParameter[] signerpara, string anchorXOffset, string anchorYOffset, string application, string documenttype, string emailsubject, string emailbody, string contractnumber, object userState) {
            if ((this.DocuSign_SignInOfficeOperationCompleted == null)) {
                this.DocuSign_SignInOfficeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_SignInOfficeOperationCompleted);
            }
            this.InvokeAsync("DocuSign_SignInOffice", new object[] {
                        pdf,
                        pagenumber,
                        estimateID,
                        versiontype,
                        printtype,
                        versionnumber,
                        signerpara,
                        anchorXOffset,
                        anchorYOffset,
                        application,
                        documenttype,
                        emailsubject,
                        emailbody,
                        contractnumber}, this.DocuSign_SignInOfficeOperationCompleted, userState);
        }
        
        private void OnDocuSign_SignInOfficeOperationCompleted(object arg) {
            if ((this.DocuSign_SignInOfficeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_SignInOfficeCompleted(this, new DocuSign_SignInOfficeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_GetRecipientViewRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DocuSign_GetRecipientViewRest(string envelopeid, EmbeddedSignerRequest re) {
            object[] results = this.Invoke("DocuSign_GetRecipientViewRest", new object[] {
                        envelopeid,
                        re});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_GetRecipientViewRestAsync(string envelopeid, EmbeddedSignerRequest re) {
            this.DocuSign_GetRecipientViewRestAsync(envelopeid, re, null);
        }
        
        /// <remarks/>
        public void DocuSign_GetRecipientViewRestAsync(string envelopeid, EmbeddedSignerRequest re, object userState) {
            if ((this.DocuSign_GetRecipientViewRestOperationCompleted == null)) {
                this.DocuSign_GetRecipientViewRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_GetRecipientViewRestOperationCompleted);
            }
            this.InvokeAsync("DocuSign_GetRecipientViewRest", new object[] {
                        envelopeid,
                        re}, this.DocuSign_GetRecipientViewRestOperationCompleted, userState);
        }
        
        private void OnDocuSign_GetRecipientViewRestOperationCompleted(object arg) {
            if ((this.DocuSign_GetRecipientViewRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_GetRecipientViewRestCompleted(this, new DocuSign_GetRecipientViewRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_GetRecipientOfEnvelope", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetRecipientResponse DocuSign_GetRecipientOfEnvelope(string envelopeid) {
            object[] results = this.Invoke("DocuSign_GetRecipientOfEnvelope", new object[] {
                        envelopeid});
            return ((GetRecipientResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_GetRecipientOfEnvelopeAsync(string envelopeid) {
            this.DocuSign_GetRecipientOfEnvelopeAsync(envelopeid, null);
        }
        
        /// <remarks/>
        public void DocuSign_GetRecipientOfEnvelopeAsync(string envelopeid, object userState) {
            if ((this.DocuSign_GetRecipientOfEnvelopeOperationCompleted == null)) {
                this.DocuSign_GetRecipientOfEnvelopeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_GetRecipientOfEnvelopeOperationCompleted);
            }
            this.InvokeAsync("DocuSign_GetRecipientOfEnvelope", new object[] {
                        envelopeid}, this.DocuSign_GetRecipientOfEnvelopeOperationCompleted, userState);
        }
        
        private void OnDocuSign_GetRecipientOfEnvelopeOperationCompleted(object arg) {
            if ((this.DocuSign_GetRecipientOfEnvelopeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_GetRecipientOfEnvelopeCompleted(this, new DocuSign_GetRecipientOfEnvelopeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_VoidEnvelopeRest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnvelopeResult DocuSign_VoidEnvelopeRest(Envelope envelope) {
            object[] results = this.Invoke("DocuSign_VoidEnvelopeRest", new object[] {
                        envelope});
            return ((EnvelopeResult)(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_VoidEnvelopeRestAsync(Envelope envelope) {
            this.DocuSign_VoidEnvelopeRestAsync(envelope, null);
        }
        
        /// <remarks/>
        public void DocuSign_VoidEnvelopeRestAsync(Envelope envelope, object userState) {
            if ((this.DocuSign_VoidEnvelopeRestOperationCompleted == null)) {
                this.DocuSign_VoidEnvelopeRestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_VoidEnvelopeRestOperationCompleted);
            }
            this.InvokeAsync("DocuSign_VoidEnvelopeRest", new object[] {
                        envelope}, this.DocuSign_VoidEnvelopeRestOperationCompleted, userState);
        }
        
        private void OnDocuSign_VoidEnvelopeRestOperationCompleted(object arg) {
            if ((this.DocuSign_VoidEnvelopeRestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_VoidEnvelopeRestCompleted(this, new DocuSign_VoidEnvelopeRestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DocuSign_DownloadDocumentForEnvelope", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DocuSign_DownloadDocumentForEnvelope(string envelopeid) {
            object[] results = this.Invoke("DocuSign_DownloadDocumentForEnvelope", new object[] {
                        envelopeid});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DocuSign_DownloadDocumentForEnvelopeAsync(string envelopeid) {
            this.DocuSign_DownloadDocumentForEnvelopeAsync(envelopeid, null);
        }
        
        /// <remarks/>
        public void DocuSign_DownloadDocumentForEnvelopeAsync(string envelopeid, object userState) {
            if ((this.DocuSign_DownloadDocumentForEnvelopeOperationCompleted == null)) {
                this.DocuSign_DownloadDocumentForEnvelopeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDocuSign_DownloadDocumentForEnvelopeOperationCompleted);
            }
            this.InvokeAsync("DocuSign_DownloadDocumentForEnvelope", new object[] {
                        envelopeid}, this.DocuSign_DownloadDocumentForEnvelopeOperationCompleted, userState);
        }
        
        private void OnDocuSign_DownloadDocumentForEnvelopeOperationCompleted(object arg) {
            if ((this.DocuSign_DownloadDocumentForEnvelopeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DocuSign_DownloadDocumentForEnvelopeCompleted(this, new DocuSign_DownloadDocumentForEnvelopeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SignerParameter {
        
        private string signerNameField;
        
        private string signerEmailField;
        
        private int routingOrderField;
        
        private int sortOrderField;
        
        private string actionField;
        
        /// <remarks/>
        public string SignerName {
            get {
                return this.signerNameField;
            }
            set {
                this.signerNameField = value;
            }
        }
        
        /// <remarks/>
        public string SignerEmail {
            get {
                return this.signerEmailField;
            }
            set {
                this.signerEmailField = value;
            }
        }
        
        /// <remarks/>
        public int RoutingOrder {
            get {
                return this.routingOrderField;
            }
            set {
                this.routingOrderField = value;
            }
        }
        
        /// <remarks/>
        public int SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Expirations {
        
        private string expireEnabledField;
        
        private string expireAfterField;
        
        private string expireWarnField;
        
        /// <remarks/>
        public string expireEnabled {
            get {
                return this.expireEnabledField;
            }
            set {
                this.expireEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string expireAfter {
            get {
                return this.expireAfterField;
            }
            set {
                this.expireAfterField = value;
            }
        }
        
        /// <remarks/>
        public string expireWarn {
            get {
                return this.expireWarnField;
            }
            set {
                this.expireWarnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reminders {
        
        private string reminderEnabledField;
        
        private string reminderDelayField;
        
        private string reminderFrequencyField;
        
        /// <remarks/>
        public string reminderEnabled {
            get {
                return this.reminderEnabledField;
            }
            set {
                this.reminderEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string reminderDelay {
            get {
                return this.reminderDelayField;
            }
            set {
                this.reminderDelayField = value;
            }
        }
        
        /// <remarks/>
        public string reminderFrequency {
            get {
                return this.reminderFrequencyField;
            }
            set {
                this.reminderFrequencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Notification {
        
        private string useAccountDefaultsField;
        
        private Reminders remindersField;
        
        private Expirations expirationsField;
        
        /// <remarks/>
        public string useAccountDefaults {
            get {
                return this.useAccountDefaultsField;
            }
            set {
                this.useAccountDefaultsField = value;
            }
        }
        
        /// <remarks/>
        public Reminders reminders {
            get {
                return this.remindersField;
            }
            set {
                this.remindersField = value;
            }
        }
        
        /// <remarks/>
        public Expirations expirations {
            get {
                return this.expirationsField;
            }
            set {
                this.expirationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TextCustomField {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomFields {
        
        private TextCustomField[] textCustomFieldsField;
        
        /// <remarks/>
        public TextCustomField[] textCustomFields {
            get {
                return this.textCustomFieldsField;
            }
            set {
                this.textCustomFieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Document {
        
        private string nameField;
        
        private int documentIdField;
        
        private string documentBase64Field;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int documentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentBase64 {
            get {
                return this.documentBase64Field;
            }
            set {
                this.documentBase64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CertifiedDeliveries {
        
        private string emailField;
        
        private string nameField;
        
        private int recipientIdField;
        
        private int routingOrderField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int recipientId {
            get {
                return this.recipientIdField;
            }
            set {
                this.recipientIdField = value;
            }
        }
        
        /// <remarks/>
        public int routingOrder {
            get {
                return this.routingOrderField;
            }
            set {
                this.routingOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InPersonSigner {
        
        private string emailField;
        
        private string nameField;
        
        private string signerNameField;
        
        private string hostEmailField;
        
        private string hostNameField;
        
        private int recipientIdField;
        
        private string clientUserIdField;
        
        private string accessCodeField;
        
        private string routingOrderField;
        
        private Tabs tabsField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string signerName {
            get {
                return this.signerNameField;
            }
            set {
                this.signerNameField = value;
            }
        }
        
        /// <remarks/>
        public string hostEmail {
            get {
                return this.hostEmailField;
            }
            set {
                this.hostEmailField = value;
            }
        }
        
        /// <remarks/>
        public string hostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
            }
        }
        
        /// <remarks/>
        public int recipientId {
            get {
                return this.recipientIdField;
            }
            set {
                this.recipientIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientUserId {
            get {
                return this.clientUserIdField;
            }
            set {
                this.clientUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string accessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string routingOrder {
            get {
                return this.routingOrderField;
            }
            set {
                this.routingOrderField = value;
            }
        }
        
        /// <remarks/>
        public Tabs tabs {
            get {
                return this.tabsField;
            }
            set {
                this.tabsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tabs {
        
        private SignHereTab[] signHereTabsField;
        
        private InitialHereTab[] initialHereTabsField;
        
        private FullNameTab[] fullNameTabsField;
        
        private DateSignedTab[] dateSignedTabsField;
        
        /// <remarks/>
        public SignHereTab[] signHereTabs {
            get {
                return this.signHereTabsField;
            }
            set {
                this.signHereTabsField = value;
            }
        }
        
        /// <remarks/>
        public InitialHereTab[] initialHereTabs {
            get {
                return this.initialHereTabsField;
            }
            set {
                this.initialHereTabsField = value;
            }
        }
        
        /// <remarks/>
        public FullNameTab[] fullNameTabs {
            get {
                return this.fullNameTabsField;
            }
            set {
                this.fullNameTabsField = value;
            }
        }
        
        /// <remarks/>
        public DateSignedTab[] dateSignedTabs {
            get {
                return this.dateSignedTabsField;
            }
            set {
                this.dateSignedTabsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SignHereTab {
        
        private string anchorStringField;
        
        private string anchorXOffsetField;
        
        private string anchorYOffsetField;
        
        /// <remarks/>
        public string anchorString {
            get {
                return this.anchorStringField;
            }
            set {
                this.anchorStringField = value;
            }
        }
        
        /// <remarks/>
        public string anchorXOffset {
            get {
                return this.anchorXOffsetField;
            }
            set {
                this.anchorXOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string anchorYOffset {
            get {
                return this.anchorYOffsetField;
            }
            set {
                this.anchorYOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InitialHereTab {
        
        private string anchorStringField;
        
        private string anchorXOffsetField;
        
        private string anchorYOffsetField;
        
        /// <remarks/>
        public string anchorString {
            get {
                return this.anchorStringField;
            }
            set {
                this.anchorStringField = value;
            }
        }
        
        /// <remarks/>
        public string anchorXOffset {
            get {
                return this.anchorXOffsetField;
            }
            set {
                this.anchorXOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string anchorYOffset {
            get {
                return this.anchorYOffsetField;
            }
            set {
                this.anchorYOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FullNameTab {
        
        private string anchorStringField;
        
        private string anchorXOffsetField;
        
        private string anchorYOffsetField;
        
        /// <remarks/>
        public string anchorString {
            get {
                return this.anchorStringField;
            }
            set {
                this.anchorStringField = value;
            }
        }
        
        /// <remarks/>
        public string anchorXOffset {
            get {
                return this.anchorXOffsetField;
            }
            set {
                this.anchorXOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string anchorYOffset {
            get {
                return this.anchorYOffsetField;
            }
            set {
                this.anchorYOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateSignedTab {
        
        private string anchorStringField;
        
        private string anchorXOffsetField;
        
        private string anchorYOffsetField;
        
        /// <remarks/>
        public string anchorString {
            get {
                return this.anchorStringField;
            }
            set {
                this.anchorStringField = value;
            }
        }
        
        /// <remarks/>
        public string anchorXOffset {
            get {
                return this.anchorXOffsetField;
            }
            set {
                this.anchorXOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string anchorYOffset {
            get {
                return this.anchorYOffsetField;
            }
            set {
                this.anchorYOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Recipients {
        
        private Signer[] signersField;
        
        private InPersonSigner[] inpersonsignersField;
        
        private CertifiedDeliveries[] certifieddeliveriesField;
        
        /// <remarks/>
        public Signer[] signers {
            get {
                return this.signersField;
            }
            set {
                this.signersField = value;
            }
        }
        
        /// <remarks/>
        public InPersonSigner[] inpersonsigners {
            get {
                return this.inpersonsignersField;
            }
            set {
                this.inpersonsignersField = value;
            }
        }
        
        /// <remarks/>
        public CertifiedDeliveries[] certifieddeliveries {
            get {
                return this.certifieddeliveriesField;
            }
            set {
                this.certifieddeliveriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Signer {
        
        private string emailField;
        
        private string nameField;
        
        private int recipientIdField;
        
        private string clientUserIdField;
        
        private string accessCodeField;
        
        private Tabs tabsField;
        
        private string embeddedRecipientStartURLField;
        
        private EmailNotification emailNotificationField;
        
        private int routingOrderField;
        
        private string deliveryMethodField;
        
        private string deliveredDateTimeField;
        
        private string signedDateTimeField;
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int recipientId {
            get {
                return this.recipientIdField;
            }
            set {
                this.recipientIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientUserId {
            get {
                return this.clientUserIdField;
            }
            set {
                this.clientUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string accessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
            }
        }
        
        /// <remarks/>
        public Tabs tabs {
            get {
                return this.tabsField;
            }
            set {
                this.tabsField = value;
            }
        }
        
        /// <remarks/>
        public string embeddedRecipientStartURL {
            get {
                return this.embeddedRecipientStartURLField;
            }
            set {
                this.embeddedRecipientStartURLField = value;
            }
        }
        
        /// <remarks/>
        public EmailNotification emailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
            }
        }
        
        /// <remarks/>
        public int routingOrder {
            get {
                return this.routingOrderField;
            }
            set {
                this.routingOrderField = value;
            }
        }
        
        /// <remarks/>
        public string deliveryMethod {
            get {
                return this.deliveryMethodField;
            }
            set {
                this.deliveryMethodField = value;
            }
        }
        
        /// <remarks/>
        public string deliveredDateTime {
            get {
                return this.deliveredDateTimeField;
            }
            set {
                this.deliveredDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string signedDateTime {
            get {
                return this.signedDateTimeField;
            }
            set {
                this.signedDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailNotification {
        
        private string emailBodyField;
        
        private string emailSubjectField;
        
        private string supportedLanguageField;
        
        /// <remarks/>
        public string emailBody {
            get {
                return this.emailBodyField;
            }
            set {
                this.emailBodyField = value;
            }
        }
        
        /// <remarks/>
        public string emailSubject {
            get {
                return this.emailSubjectField;
            }
            set {
                this.emailSubjectField = value;
            }
        }
        
        /// <remarks/>
        public string supportedLanguage {
            get {
                return this.supportedLanguageField;
            }
            set {
                this.supportedLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Envelope {
        
        private string envelopeidField;
        
        private Recipients recipientsField;
        
        private string emailSubjectField;
        
        private string emailBlurbField;
        
        private Document[] documentsField;
        
        private string statusField;
        
        private CustomFields customfieldsField;
        
        private string allowReassignField;
        
        private Notification notificationField;
        
        private string voidedreasonField;
        
        /// <remarks/>
        public string envelopeid {
            get {
                return this.envelopeidField;
            }
            set {
                this.envelopeidField = value;
            }
        }
        
        /// <remarks/>
        public Recipients recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
            }
        }
        
        /// <remarks/>
        public string emailSubject {
            get {
                return this.emailSubjectField;
            }
            set {
                this.emailSubjectField = value;
            }
        }
        
        /// <remarks/>
        public string emailBlurb {
            get {
                return this.emailBlurbField;
            }
            set {
                this.emailBlurbField = value;
            }
        }
        
        /// <remarks/>
        public Document[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public CustomFields customfields {
            get {
                return this.customfieldsField;
            }
            set {
                this.customfieldsField = value;
            }
        }
        
        /// <remarks/>
        public string allowReassign {
            get {
                return this.allowReassignField;
            }
            set {
                this.allowReassignField = value;
            }
        }
        
        /// <remarks/>
        public Notification notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        public string voidedreason {
            get {
                return this.voidedreasonField;
            }
            set {
                this.voidedreasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRecipientResponse {
        
        private Signer[] signersField;
        
        private string recipientCountField;
        
        private string currentRoutingOrderField;
        
        /// <remarks/>
        public Signer[] signers {
            get {
                return this.signersField;
            }
            set {
                this.signersField = value;
            }
        }
        
        /// <remarks/>
        public string recipientCount {
            get {
                return this.recipientCountField;
            }
            set {
                this.recipientCountField = value;
            }
        }
        
        /// <remarks/>
        public string currentRoutingOrder {
            get {
                return this.currentRoutingOrderField;
            }
            set {
                this.currentRoutingOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmbeddedSignerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvelopeResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ModelBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmbeddedSignerRequest : ModelBase {
        
        private int recipientIdField;
        
        private System.Guid envelopeIdField;
        
        private string userNameField;
        
        private string emailField;
        
        private string clientUserIdField;
        
        private string authenticationMethodField;
        
        private string authenticationInstantField;
        
        private string returnUrlField;
        
        /// <remarks/>
        public int RecipientId {
            get {
                return this.recipientIdField;
            }
            set {
                this.recipientIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid EnvelopeId {
            get {
                return this.envelopeIdField;
            }
            set {
                this.envelopeIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string ClientUserId {
            get {
                return this.clientUserIdField;
            }
            set {
                this.clientUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationMethod {
            get {
                return this.authenticationMethodField;
            }
            set {
                this.authenticationMethodField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationInstant {
            get {
                return this.authenticationInstantField;
            }
            set {
                this.authenticationInstantField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvelopeResult : ModelBase {
        
        private string envelopeIdField;
        
        private string uriField;
        
        private System.DateTime statusDateTimeField;
        
        private string statusField;
        
        /// <remarks/>
        public string EnvelopeId {
            get {
                return this.envelopeIdField;
            }
            set {
                this.envelopeIdField = value;
            }
        }
        
        /// <remarks/>
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StatusDateTime {
            get {
                return this.statusDateTimeField;
            }
            set {
                this.statusDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_CreateAndSendEnvelopeCompletedEventHandler(object sender, DocuSign_CreateAndSendEnvelopeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_CreateAndSendEnvelopeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_CreateAndSendEnvelopeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvelopeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvelopeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_SignInOfficeCompletedEventHandler(object sender, DocuSign_SignInOfficeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_SignInOfficeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_SignInOfficeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvelopeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvelopeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_GetRecipientViewRestCompletedEventHandler(object sender, DocuSign_GetRecipientViewRestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_GetRecipientViewRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_GetRecipientViewRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_GetRecipientOfEnvelopeCompletedEventHandler(object sender, DocuSign_GetRecipientOfEnvelopeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_GetRecipientOfEnvelopeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_GetRecipientOfEnvelopeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetRecipientResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetRecipientResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_VoidEnvelopeRestCompletedEventHandler(object sender, DocuSign_VoidEnvelopeRestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_VoidEnvelopeRestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_VoidEnvelopeRestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvelopeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvelopeResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DocuSign_DownloadDocumentForEnvelopeCompletedEventHandler(object sender, DocuSign_DownloadDocumentForEnvelopeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DocuSign_DownloadDocumentForEnvelopeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DocuSign_DownloadDocumentForEnvelopeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591