//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metricon.Silverlight.MetriconRetailSystem.Host.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:50085/MetriconSales.asmx")]
        public string Metricon_Silverlight_MetriconRetailSystem_Host_MetriconSalesWebService_MetriconSales {
            get {
                return ((string)(this["Metricon_Silverlight_MetriconRetailSystem_Host_MetriconSalesWebService_MetriconSa" +
                    "les"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:50085/PMO-006WebService/DocuSignWebService.asmx")]
        public string Metricon_Silverlight_MetriconRetailSystem_Host_DocuSignWebService_DocuSignWebService {
            get {
                return ((string)(this["Metricon_Silverlight_MetriconRetailSystem_Host_DocuSignWebService_DocuSignWebServ" +
                    "ice"]));
            }
        }
    }
}
