name: MRS Build

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to  # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1            
   

      # Install Silverlight Toolkit
      #- name: Install Silverlight Toolkit
      #  run: dotnet add package SilverlightToolkit-All --version 4.2010.4

      # - name: Install MS SilverLight SDK
      #   run: msiexec /i silverlight.msi ALLUSERS=2 /qn /LiV Silverlight5.log
      #   working-directory: ExternalBinaries

      # call dotnet restore
      - name: Install Silverlight SDK
        run: choco install -y silverlight5sdk  

      # Build the SL website
      - name: MRS Solution Build
        run: msbuild $env:Solution_Path -p:Configuration=Release -p:DeployOnBuild=True -p:PackageAsSingleFile=true -p:IgnoreDeployManagedRuntimeVersion=True -p:PackageFileName=$env:TargetPkgFileName
        env:
          Solution_Path: Metricon.Silverlight.MetriconRetailSystem.Host/Metricon.Silverlight.MetriconRetailSystem.Host.csproj
          TargetPkgFileName: MRS-SilverLight-${{ github.run_id }}.zip 

      - name: Upload MRS Silverlight build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MRS Silverlight Package ${{ github.run_id }}
          path: Metricon.Silverlight.MetriconRetailSystem.Host\MRS-SilverLight-${{ github.run_id }}.*

      # Build the SL website
      - name: MRS Solution Build
        run: msbuild $env:Solution_Path -p:Configuration=Release -p:DeployOnBuild=True -p:PackageAsSingleFile=true -p:IgnoreDeployManagedRuntimeVersion=True -p:PackageFileName=$env:TargetPkgFileName
        env:
          Solution_Path: Metricon.WCF.MetriconRetailSystem.Host/Metricon.WCF.MetriconRetailSystem.Host.csproj
          TargetPkgFileName: MRS-WCF-${{ github.run_id }}.zip 

      - name: Upload MRS WCF build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MRS WCF Package ${{ github.run_id }}
          path: Metricon.WCF.MetriconRetailSystem.Host\MRS-WCF-${{ github.run_id }}.*